project:
  type: website
  output-dir: _site

website:
  title: "Copyleft Cultivars"
  description: "Protect, publish, and preserve vulnerable plants — using copyleft, research, and education."
  favicon: images/logo.png
  navbar:
    logo: images/logo.png
    title: "Copyleft Cultivars"
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        menu:
          - text: "Our Mission"
            href: about.qmd#our-mission
          - text: "Who we are"
            href: about.qmd#who-we-are
          - text: "The Commons"
            href: about.qmd#the-commons
      - text: "Resources"
        menu:
          - text: "Freedom Bag Tag"
            href: preservation.qmd#freedom-bag-tag
          - text: "Agriculture Assistant"
            href: initiatives.qmd#regenerative-agriculture-assistant
      - text: "The Regenerative Relations Initiative"
        href: regenerative-relations-initiative.qmd
      - text: "Genomic Galaxy"
        href: genomic-galaxy.qmd
      - text: "Support"
        menu:
          - text: "Donate"
            href: support.qmd#donate
          - text: "Volunteer"
            href: support.qmd#volunteer
          - text: "Patreon"
            href: https://www.patreon.com/CopyleftCultivarsNonprofit
            target: _blank
            rel: noopener
  page-footer:
    border: true
    left: |
      Copyright © 2025 Copyleft Cultivars.
      Except where otherwise noted, all works and content on this site are licensed under [CC-BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) + Copyleft Cultivars commercial rights and responsibilities.
    right: |
      Copyleft Cultivars is a registered 501(c)3 non-profit organization. Donations are tax-deductible. EIN: 87-3765168

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    toc-location: right
    anchor-sections: true
    smooth-scroll: true
