project:
  type: website
  output-dir: _site

website:
  title: "Copyleft Cultivars"
  description: "Protect, publish, and preserve vulnerable plants — using copyleft, research, and education."
  favicon: images/logo.png
  navbar:
    logo: images/logo.png
    title: "Copyleft Cultivars"
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: preservation.qmd
        text: Preservation
      - href: initiatives.qmd
        text: Initiatives
      - href: events.qmd
        text: Events
      - href: news.qmd
        text: News
      - href: faq.qmd
        text: FAQ
      - href: support.qmd
        text: Support
  page-footer:
    border: true
    left: |
      Copyright © 2025 Copyleft Cultivars.
      Except where otherwise noted, content is licensed under
      [CC-BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/).
    center:
      - text: "Contact"
        href: mailto:copyleftcultivars@gmail.com
      - text: "Donate"
        href: https://www.patreon.com/CopyleftCultivarsNonprofit
      - text: "Subscribe"
        href: https://docs.google.com/forms/d/e/1FAIpQLSehSxLrJkMRW9D8YgBJ9zqYBNcYPuu7aBUuEPVdqUOLR93XMw/viewform

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    toc-location: right
    anchor-sections: true
    smooth-scroll: true



