project:
  type: website
  output-dir: _site

website:
  title: "Copyleft Cultivars"
  description: "Protect, publish, and preserve vulnerable plants — using copyleft, research, and education."
  favicon: images/logo.png
  navbar:
    logo: images/logo.png
    title: "Copyleft Cultivars"
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        menu:
          - text: "Mission"
            href: about.qmd#our-mission
          - text: "Who we are"
            href: about.qmd#who-we-are
          - text: "The Commons"
            href: about.qmd#a-community-commons-for-vulnerable-plants
      - text: "Resources"
        menu:
          - text: "Freedom Bag Tag"
          - text: "V2 (English & Spanish)"
            href: preservation.qmd#freedom-bag-tag
          - text: "OGV"
            href: preservation.qmd#freedom-bag-tag
          - text: "---"
          - text: "Agriculture Assistant"
            href: https://huggingface.co/spaces/CopyleftCultivars/natural-farming-chat-V4
            target: _blank
            rel: noopener
      - text: "Regenerative Relations Initiative"
        href: initiatives.qmd#regenerative-relations-initiative
      - text: "Genomic Galaxy"
        href: faq.qmd#what-will-copyleft-cultivars-do-with-the-genetic-sequences-of-submitted-cultivars
      - text: "FAQ"
        href: faq.qmd
      - text: "Support"
        menu:
          - text: "Donate"
            href: support.qmd#donate
          - text: "Volunteer"
            href: support.qmd#volunteer
          - text: "Patreon"
            href: https://www.patreon.com/CopyleftCultivarsNonprofit
            target: _blank
            rel: noopener
  page-footer:
    border: true
    left: |
      Copyright © 2025 Copyleft Cultivars.
      Except where otherwise noted, content is licensed under
      [CC-BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/).
    center:
      - text: "Contact"
        href: mailto:copyleftcultivars@gmail.com
      - text: "Donate"
        href: https://www.patreon.com/CopyleftCultivarsNonprofit
      - text: "Subscribe"
        href: https://docs.google.com/forms/d/e/1FAIpQLSehSxLrJkMRW9D8YgBJ9zqYBNcYPuu7aBUuEPVdqUOLR93XMw/viewform

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    toc-location: right
    anchor-sections: true
    smooth-scroll: true
