---
title: "FAQ"
---

## What is Copyleft?

According to GNU (who originated the copyleft license widely used in software),
"Copyleft is a general method for making a program (or other work) free (in the
sense of freedom, not 'zero price'), and requiring all modified and extended
versions of the program to be free as well."

Copyleft is a system of open-source protection which uses copyright law to defend
freedom and collaboration. The term Copyleft is a play on the word Copyright,
because it is valid by copyright and contract laws yet flips copyright on its head
by having an open collaborative approach to using those rights.

## What is the Open Source Plants Movement?

The Open Source Plants Movement is a new wave of OpenBio movement which brings
together the traditional open-source sentiments of strength through community,
mutual aid, and freedom, with important plant-related issues such as farmer rights,
indigenous perspectives, and the realities of plant breeding. The OpenBio movement
came out of the open-source software movement and has gotten global recognition in
recent years.

## How does Copyleft apply to plant medicines?

It is reasonable to infer that copyright rights are due to plant breeders who write
genetic code in a similar way as software programmers and film script writers have
copyright rights.

By that understanding of copyright law, when an author, programmer, or breeder
creates a new work of art and records it — i.e. a new cultivar is produced,
genetically sequenced, and published — the author/programmer/breeder has a right to
set use-terms and copyright terms when they distribute it. These are very difficult
to draft, organize, and enforce as an individual but very doable as a community
coalition.

Copyleft uses those use-terms and rights to protect its code/genetics as an
open-source community good and thereby deter issues for the creator as well as
users, and prevent prohibition-by-patent, entrenching the freedom of its users and
the right to repair.

## How do we help the preservation of plant medicine genetics?

In a world which is rapidly changing, the genetics information and history of
medicinal plant cultivars/strains is highly threatened. We believe that greater
freedom of use and a framework which encourages sharing for mutual benefit leads
naturally to a more stable population of important cultivars kept alive through many
hands in the community.

We can encourage this distribution of vital cultivars while we start to protect,
document, publish, and make usable the vast array of information about these
cultivars being developed around the world, in a way which puts the community and
the accessibility of the information front-and-center, accelerating development to
the benefit of all members of the ecosystem.

We do this in a way which avoids the single point of failure issue of fragility in
privatized pockets of information, instead championing open freedom-assured
community sharing of information and material access, thereby improving long-term
survival and proliferation of important diverse genetic material and plant medicine
information.

## How does the community benefit from our Copyleft approach?

Among additional benefits to the community, the Copyleft systems may:

- Protect and deter from predatory IP litigation (as seen to have devastated many
  industries such as corn);
- Defend small actors from big corporations;
- Assure biodiversity and open progress of vulnerable plants;
- Protect and deter from prohibition-by-patent, which is inherently governmentally
  enforced;
- Prevent genetic bottlenecking;
- Make large amounts of genetic and cultivation information largely available for
  scientific research and public breeding development worldwide;
- Create a system for centralized certification of genetic authenticity;
- Resolve interbreeder cultivar origin disputes;
- Offer community preservation support; and
- Assure availability of freedom-assured and constantly updating breeding stock for
  new and established breeders.

## How do open source seeds benefit farmers?

The Open Source Seed Initiative, a group which protects vegetables in a similar but
less enforceable method to our system, put it very well:

> "Pledged seed preserves the farmer's right to save, replant, share, breed, and
> sell seed. It is this fundamental right that is now being eroded globally as
> transnational seed companies push for the worldwide expansion of restrictive seed
> laws and intellectual property rights. The independent farmer has long been the
> basis of food security for local communities and in many countries is the first
> line of defense against hunger. With use-restricted seeds, a farmer is unable to
> plant a new crop without purchasing new seed from an outside supplier. Whether the
> cause is cataclysm or merely economics, no seed means the farmer produces no crop.
> Open source, unrestricted seed allows the farmer to plant again if the patented
> seeds are unavailable, unwanted, or unaffordable."

## Why do breeders & cultivators need protection and defense for the medicinal plant cultivars they work with?

Once the Federal Court System is open to medicinal plants IP litigation, as with all
established industries as they emerge, breeders and cultivators will face many new
dangers. These dangers are exemplified by these four facts:

- "More than 10,000 [tech] companies have been sued at least once by a patent troll,
  and patent trolls file 84 percent of high-tech patent lawsuits a year."
  (TechCrunch, May 4, 2017.)
- The average cost of patent litigation is $2.8 Million USD (The American
  Intellectual Property Law Association).
- LLCs and businesses have no right to self-representation in court, thus must pay
  exhaustive lawyers' fees or lose litigation by default.
- 4,204 IP lawsuits were fought in 2020 alone (WIPO.int).

Breeders and cultivators must ask themselves, "Do I have the financial war chest,
legal expertise, and personal stress tolerance to handle being involved in Federal
Court Intellectual Property (IP) litigation?"

## How can Copyleft Cultivars protect the people and plant medicines within the commons?

Creating a nonprofit organization with intervenor rights via the copyleft license
allows for the nonprofit to step into legal issues related to the Copyleft protected
cultivars. This way, the nonprofit can enable community coalitions, allowing many
individuals to pull together in protection and defense of each other (your fellow
community members), the community commons ecosystem, and the people who are a part of
it. This also helps assure the continued biodiversity of the medicine plants and
gather data that will be available for research that benefits the community.

## Can I still make money with my seeds and/or plant products if they are open source?

Yes! Breeders and cultivators can still sell their products as they would otherwise,
now with the additional peace of mind knowing they are protected and that they have
contributed to a brighter future for the community and for themselves. This may even
increase real market value and sales, because of the plethora of consumer benefits,
as it has with open-source software.

## How can the Copyleft license facilitate the safety of my business?

The Copyleft License is crafted to help assure your safety and protect you in your
breeding, production, sales, services, etc. This is done by protecting you and the
pledged genetics from predatory litigation, prohibition-by-patent, privatization,
corporate IP takeover, baseless seed litigation (as seen with Monsanto with 400+
court cases against small corn farmers), and other IP issues common in most
established industries.

As the Beneficiary Intervenor and Protector of your contributions to the community
common, Copyleft Cultivars has your back and the back of those who use the
freedom-assured Copylefted varietals, thus letting you stay out of any copyright
fight and allowing you to focus on your life and livelihood instead. This protection
can be seen as value-added for the product you distribute and the cultivars you
create.

## Ok, but is open source an effective business model?

Yes, open source is a very effective business model. It consistently gives
competitive advantage and larger market share. In fact, open-source software now
holds the largest market share of the USD $429.59 Billion software market. Eric
Raymond has written extensively on open-source economics, why open-source software
has succeeded in the market over closed source, and how companies can implement
open-source strategies for optimal success. He stated in *The Magic Cauldron* essay:

> "Open, shared infrastructure gives its participants competitive advantages. One is
> lower cost per participant to produce salable products and services. Another is a
> market position that reassures customers that they are much less likely to be stuck
> with orphaned technology as a result of one vendor's change in strategy or tactics."

And further,

> "We observed that open-source infrastructure creates trust and symmetry effects
> that, over time, will tend to attract more customers and to outcompete
> closed-source infrastructure; and it is often better to have a smaller piece of
> such a rapidly-expanding market than a bigger piece of a closed and stagnant one.
> Accordingly, an open source play for ubiquity is quite likely to have a higher
> long-term payoff than a closed-source play for rent from intellectual property."

## Is Copyleft Cultivars' approach compatible or adversarial with other intellectual property protections, such as trademarking and patenting?

Our Copyleft system is compatible and complementary with most other forms of
intellectual property protections, so long as they refrain from perpetrating
predatory litigation against the copyleft community at-large, and respect the
freedom-assuring terms of use when used in combination with the copyleft system.

Trademarking of "strain names," for example, may offer additional protection and
economic benefits for breeders and cultivators, while at the same time one could also
register the genetics of that cultivar/strain in the copyleft cannabis system here.

We hope to create a community coalition, an alliance of sorts, between the Copyleft
Cannabis Project, other open-source projects, NFT systems, defensive patent holders,
and PVPA rights holders in the medicinal plants space that will together support each
other and prevent in-fighting, thereby creating a robust backbone for community
defense on a larger scale.

## If I pledge a cultivar, do I need to release the seeds publicly?

No, but it may be beneficial to the future of the cultivar. The standard Copyleft
licenses do not affect nor require anything of how openly you do or do not distribute
it, as long as, if you do, you include the Copyleft license terms as part of your
distribution and abstain from patenting or otherwise restricting it.

We are exploring creating other licenses that could be chosen from, which add ethical
duty of care to prevent human rights abuses by users of the cultivars, and ones which
mandate physical seed sharing. The standard CCGL will not mandate seed sharing or any
replication of the seeds, but does encourage it.

## What about strains/varietals which have already been publicly released?

New strains/cultivars must be pledged prior to wide public distribution in order to
be protected by Copyleft. We cannot retroactively protect already-released cultivars,
as they are either under other use-terms or in the public domain by default.

Cultivars in the public domain remain vulnerable to trolling, piracy, and future
forms of prohibition by privatization. Under the current laws in place, we cannot
intervene to defend you from litigation involving public domain cultivars. The one
exception is tester seed packets which were distributed in limited quantities along
with an explicit written notice that they are "Tester Seeds" or "For Test Purposes
Only."

## Can you help me with legal troubles involving non-copylefted cultivars?

Unfortunately not. The Beneficiary Intervenor Status of the Copyleft Pledge gives us
the ability to intervene in civil cases involving only the intellectual property asset
(the cultivar, traits, and genetics, in this case). Thus we can only defend breeders,
cultivators, and other groups that use Copyleft pledged and protected cultivars which
are in our database.

## If I breed with a Copyleft protected cultivar, what is the IP status of the offspring?

The offspring of a Copyleft protected cultivar will themselves also be Copyleft
protected. That means if they are distributed they must be distributed with the same
Copyleft terms/license/protection, and prior to distribution should be logged into the
Copyleft system. Because the parentage is already genetic-tested and published, the
submission of genetic sequencing data may not be necessary, but the opportunity to do
genetic sequencing should be made available to the Copyleft Cultivars organization for
publication. We are in discussions with cannabis genetics experts to determine how many
generations from a databased parent breeders may go without needing to again test the
genetics and submit them to the database to continue the protections and contribute to
scientific advancement.

## How does this approach protect from issues seen previously with other groups' public fiascos related to genomic galaxy building?

Unlike other groups which have caved under profit-motive when creating an open genetic
nexus for cannabis, we are completely free of any direct founding influence from any
for-profit company.

We are a small group of individual community members, many of us from the medical
marijuana movement, driven by the desire to help protect the medicinal plants and
medicinal plant communities which have helped us in so many ways. We are growers and
breeders who started this project because we love this plant and the people who work
with it. We love freedom and we love the powerful community that can be created in
spaces of assured freedom.

## Why a nonprofit?

To protect the integrity of our mission, the organization will be a nonprofit, bound
by its filings to serve the community instead of having any shareholders. The legal
documents which form the backbone of the organization are drafted very carefully to
make profit-driven exploitation and corporate piracy impossible.

## Will the Copyleft Cultivars database ever be used by the organization for private breeding of any sort?

Notably, we will never use, and won't even be able to use, the genetic information
submitted to develop privatized cultivars nor to pitch investors secret proprietary
breeding programs, as other groups have done. Pledging cultivars via a Copyleft
Creative Commons license legally prevents anyone — including our organization itself —
from privatizing them or their offspring.

(Note, this approach still allows use of the copylefted cultivars for legitimate
profit-making, such as producing products, i.e. seeds or flower, as explained briefly
in other questions here.)

## What will Copyleft Cultivars do with the genetic sequences of submitted cultivars?

We aim to assemble a public genetics nexus with submitted cultivars. The genetic
information will be put in the genetic library which links it to similar genetic
strains/varietals in an interactive data visualization, made publicly available. In
this, we will register the breeder as the public originator of the genetics, thereby
putting to rest any community controversy regarding who bred which strain and the
breeding history if bred from already-pledged cultivars. Ideally we will then be able
to link to allied seed banks where they will offer certified seeds for the
copyleft-protected cultivars/strains.

## What will be the notice for Copyleft Cultivars protected seeds?

There will be a bag tag (use license label) for each license. The core protection
license, CCGL (Copyleft Cannabis Genetic-backed License), has a bag tag in its main
text. We also have a community-created stand-alone bag tag that carries some but not
all of the benefits and protections of the CCGL and is much less solidly enforceable.

## How does this benefit breeders contracted or employed by private companies?

Agreeing with your employer or contractor to Copyleft Pledge the cultivars you develop
in your work with them has many benefits for you and your employer. For breeders, it
will protect them from losing access to their work upon termination, which is
unfortunately common with closed-source agriculture. A quick overview of the most
expensive IP litigation cases involving strawberries shows this is a major and
recurring concern from contracted or employed breeders. We are working on a form
contract that can be used in this case to protect the breeder and the other parties in
formal breeding collaborations.

## What legal jurisdiction is / will this be in?

We are formed as a domestic nonprofit in Oregon because of the location of some of our
founders and the favorable jurisdiction to this type of work, medicinal plants
freedoms, and farmer freedom. Our systems will serve the whole country and, if
possible, also the whole world, toward interconnecting the global medicinal plant
ecosystem to prioritize farmer freedom, collaboration, and common good!

## Will there be a dispute process?

Yes there will be, and it will first have a non-court arbitration option through our
organization, facilitated by the genetics database and submitted evidence. This will
avoid costly court fees and liability for each party while resolving the issue for the
community. If absolutely necessary to protect the integrity of the copyleft
protections and the database, civil courts may be used. We are working to envision this
process and welcome your input.

## Can I charge royalties for commercial use of the genetics I submit to Copyleft Cultivars?

Our license is intended to assure freedom, without affecting your ability to make money
from your work. If you wish to add commercial use-terms for royalties you may be free
to pursue creating those terms with separate legal services. We cannot give you legal
advice regarding royalties on copyleft-protected cultivars. At all times, adherence to
the license status of the cultivars is absolutely necessary. If you'd like to chat with
us about pursuing this, please have your qualified legal assistance team or a law firm
representing you reach out to our organization to explore that possibility,
[copyleftcultivars@gmail.com](mailto:copyleftcultivars@gmail.com).

## Where can I get Copyleft Cultivars pledged seeds?

Copyleft Cultivars is not a seed company. Rather, we will work with seed companies who
are interested in supporting our mission. When up and running, we will link cultivars
in our public database to where they are available on seed banks. They may also be
available directly from the plant breeder, depending on the variety. If you are a seed
company who would like to be more directly involved, please email
[copyleftcultivars@gmail.com](mailto:copyleftcultivars@gmail.com).

## How can I contribute skills or funds to make this happen?

If you have skills you'd like to contribute, or funds, to Copyleft Cultivars, please
email us at [copyleftcultivars@gmail.com](mailto:copyleftcultivars@gmail.com) or join
the [Discord](https://discord.gg/jFcW6ZrK). We are especially looking for programmers
and attorneys with experience working with Creative Commons or plant IP, and
experienced nonprofit professionals. We very much appreciate the help because we are a
small but dedicated of-the-community-for-the-community team.

---

Except where otherwise noted, all works and content on this site are licensed under
[CC-BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) +
[Copyleft Cultivars commercial rights and responsibilities](https://docs.google.com/document/d/1Gd6HGxs9KnS8nBdjXq5GLf46l6HCpr1xTKfTaF2yfrA/edit?usp=sharing).
