---
title: "Support"
---

## Donate

**Your financial contribution is what makes this possible.**

To date, we are 100% crowdfunded, and we rely on YOU and generous people like you to
make this project work. We very much appreciate the help because we are a small (and
dedicated) of-the-community-for-the-community collaboration, and we depend on community
support to achieve our mission.

Our organization accepts donations through our fiscal sponsor,
[Pro Arts Commons](https://www.proartscommons.org/).

To donate to Copyleft Cultivars, click the button below. When making a donation, write
"For Copyleft Cultivars" to ensure your donation reaches our organization.

[Donate Now](https://www.patreon.com/CopyleftCultivarsNonprofit){.btn .btn-primary role="button"}

## Copyleft Cultivars Apparel

**Ethically produced. Super comfy. Kaleidoscopic.**

Copyleft Cultivars Apparel — designed by our very own co-founder @SolshineGrowing <3

[Shop Now](https://www.contrado.com/stores/solshine){.btn .btn-outline-primary role="button"}

## Volunteer

**Join our community collaboration.**

We are seeking genomics experts, lawyers, and nonprofit professionals. Email us at
[copyleftcultivars@gmail.com](mailto:copyleftcultivars@gmail.com) and share how you can
contribute to our efforts!

## Seed Auctions

We are thrilled to share that Strainly is supporting Copyleft Cultivars' fundraising
efforts through allowing independent breeders to host seed auctions of Copyleft
protected varietals. Check it out & support today!

[Bid](https://www.strainly.io/en/solshinegrowing){.btn .btn-outline-primary role="button"}

---

Except where otherwise noted, all works and content on this site are licensed under
[CC-BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) +
[Copyleft Cultivars commercial rights and responsibilities](https://docs.google.com/document/d/1Gd6HGxs9KnS8nBdjXq5GLf46l6HCpr1xTKfTaF2yfrA/edit?usp=sharing).
